### ISSUE TITLE
Chart service seems to be broken

### ISSUE THREAD

**Issue by Raiondesu** [apertureless/npm-stats#18]
Today, 26-th of may, 2018, npm-stats.org seems to be not showing charts anymore.
There are no errors in console and charts are not showing up (at least in Chrome and Opera - both mobile and desktop).

Tested with a bunch of Vue packages, including:
- vue-meta
- vue-simple-suggest
- vue
- vuex

@apertureless, can you confirm this?

**Comment by apertureless** [comment]
Should be fixed now.

**Comment by Raiondesu** [comment]
Seems like it is. Thank you for a great starts website, by the way. :+1:
